import Head from "next/head";
import { Header } from "../src/components/Header";
import { TransactionForm } from "../src/components/TransactionForm";
import styled from "styled-components";
import { TransactionProvider } from "../src/contexts/TransactionContext";
import { ConnectWallet } from "../src/components/ConnectWallet";

const Main = styled.div`
  padding: 3rem;
  background-color: white;
  min-height: 100vh;
`;

export const Home = () => {
  return (
    <TransactionProvider>
      <Head>
        <title>Project Web3.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Main>
        <ConnectWallet />
        <TransactionForm />
      </Main>
    </TransactionProvider>
  );
};

export default Home;
